---
- name: Trabajar con lineinfile
  hosts: ubuntu1
      
  tasks:
  - name: Copiar un fichero sencillo de ejemplo
    copy:
      src: ejemplo.txt
      dest: /tmp/ejemplo.txt

  - name: Añadir un línea al fichero
    ansible.builtin.lineinfile:
      path: /tmp/ejemplo.txt
      line: 4 Otro otro ejemplo

  - name: Cambiar la línea1
    ansible.builtin.lineinfile:
      path: /tmp/ejemplo.txt
      search_string: 1 Ejemplo
      line: He cambiado la linea 1

  - name: Borrar la línea 2
    ansible.builtin.lineinfile:
      path: /tmp/ejemplo.txt
      search_string: 2 Otro Ejemplo
      state: absent

  - name: Reemplazar la linea 3
    ansible.builtin.lineinfile:
      path: /tmp/ejemplo.txt
      regexp: '^3 Otro otro Ejemplo'
      line: "Cambiado con REGEX"