---
- name: Until
  hosts: debian1

  tasks:
  
  - name: Repite una tarea has que se cumple la condición
    ansible.builtin.shell: 
      cmd: cat /tmp/tarea1
    register: result
    until: result.stdout=="Fin de Proceso" #mientras la salida del comando anterior no sea fin de proceso continua. 
    #mientras el cat devuelva fin de procesa se para el Bucle
    changed_when: false
    retries: 5
    delay: 2