---
- name: Probar vault creando usuario y claves
  hosts: debian1
  vars_files: usuarios.yaml
  
  tasks:
    - name: Crear usuarios
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.pass | password_hash('sha512') }}"
        state: present
      loop: "{{ usuarios }}"
