---
- name: Instalar y ejecutar Lynis en Rocky Linux
  hosts: 192.168.99.22
  become: yes
  tasks:

    - name: Instalar Lynis
      yum:
        name: lynis
        state: present

    - name: Ejecutar auditoría con Lynis
      command: lynis audit system
      register: lynis_result
      ignore_errors: yes  # Por si lanza advertencias, que no falle el playbook

    - name: Mostrar resumen de resultados
      debug:
        msg: "{{ lynis_result.stdout_lines }}"

