- name: Montar un sistema de ficheros
  hosts: localhost
  become: true
  gather_facts: true 

  tasks:
  
  - name: Crear punto de montaje
    ansible.builtin.file:
      path: /datos
      state: directory

  - name: Montar el sistema de ficheros
    ansible.posix.mount:
      path: /datos
      src: /dev/sdb
      fstype: ext4
      state: mounted