---
- name: Practica storage
  hosts: localhost
  become: true
  gather_facts: true

  vars:
    discos:
      - /dev/nvme0n1
      - /dev/nvme0n2
    particiones:
      - /dev/nvme0n1p2 
      - /dev/nvme0n2p2
    vg: grupo2
    lv:
      - lvol1
      - lvol2
    filesystem: ext4
    folders:
      - /imagenes
      - /videos
  
  tasks:
  - name: agregar particiones a cada disco
    tags: add_partitions
    loop: "{{discos}}"
    community.general.parted:
      device: "{{item}}"
      number: 2
      part_start: 5GiB
      part_end: 9GiB
      state: present

  - name: crear un vg
    tags: add_vg
    community.general.lvg:
      vg: "{{ vg }}"
      pvs: "{{ particiones }}"

  - name: crear lv
    tags: add_lv
    loop: "{{ lv }}"
    community.general.lvol:
      vg: "{{ vg }}"
      lv: "{{ item }}"
      size: 4000
  - name: crear el filesystem
    tags:  crear filesystem
    loop:
    - /dev/{{ vg }}/{{ lv[0] }}
    - /dev/{{ vg }}/{{ lv[1] }}
    community.general.filesystem:
      dev: "{{ item }}"
      fstype: "{{ filesystem }}"
      state: present
  - name: Crear los directorios
    tags: create_folders
    loop: "{{folders}}"
    ansible.builtin.file:
      path: "{{item}}"
      state: directory

  - name: Montar el sistema de ficheros
    tags: mount_fs
    loop:
    - /dev/{{vg}}/{{lv[0]}}:{{folders[0]}}
    - /dev/{{vg}}/{{lv[1]}}:{{folders[1]}}
    ansible.posix.mount:
      src: "{{ item.split(':')| first }}"
      path: "{{ item.split(':')| last }}"
      fstype: "{{ filesystem }}"
      state: mounted
