---
- name: Instalar software 
  hosts: all
  vars_files:
     - software_rocky.yaml
     - software_ubuntu.yaml

  tasks:

  - name: actualizar repositorios
    ansible.builtin.apt:
      update_cache: yes
      

    when: ansible_distribution=='ubuntu'
  - name: Instalar ubuntu
    ansible.builtin.apt:
      name: "{{item}}"
      state: present
    loop: "{{software_ubuntu}}"
    when: ansible_distribution=='ubuntu' 
  
  
  - name: Instalar rocky
    ansible.builtin.yum:
      name: "{{item}}"
      state: present
    loop: "{{software_rocky}}"
    when: ansible_distribution=='Rocky'
       